DATA = {
    "state": {
        "name": "Andhra Pradesh",
        "capital": "Amaravati",
        "description": "Known as the 'Rice Bowl of India' — famous for its incredibly rich temple heritage, deep-rooted Buddhist history, and a stunningly long eastern coastline.",
    },
    "cities": [
        {
            "name": "Visakhapatnam",
            "places": [
                {
                    "name": "RK Beach (Ramakrishna Beach)",
                    "categories": ["nature", "beach", "leisure"],
                    "description": "A bustling urban beach on the Bay of Bengal, known for its golden sands, evening promenades, and the unique INS Kursura Submarine Museum.",
                    "historical_significance": "Named after the nearby Ramakrishna Mission ashram. It houses the INS Kursura, India's fifth submarine, which was turned into the first submarine museum in South Asia after being decommissioned in 2001.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry to beach (Submarine Museum: ₹50 approx.)",
                    "timings": "Open 24 hours (Museum: 2:00 PM – 8:30 PM, closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=RK+Beach+Visakhapatnam",
                    "nearby_attractions": "INS Kursura Submarine Museum\nTU 142 Aircraft Museum\nKailasagiri",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Borra Caves",
                    "categories": ["nature", "caves", "geological_wonder"],
                    "description": "Magnificent million-year-old limestone caves located in the Ananthagiri hills of the Araku Valley, featuring stunning stalactite and stalagmite formations.",
                    "historical_significance": "Discovered in 1807 by William King George of the Geological Survey of India. The caves are deeply revered by the local indigenous tribes due to a naturally formed Shiva Lingam inside.",
                    "best_time_to_visit": "November to March",
                    "entry_fee": "₹80 (Adults), ₹60 (Children)",
                    "timings": "10:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Borra+Caves+Andhra+Pradesh",
                    "nearby_attractions": "Araku Valley\nKatiki Waterfalls\nCoffee Museum",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Tirupati",
            "places": [
                {
                    "name": "Sri Venkateswara Swamy Vaari Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "A landmark Vaishnavite temple situated on the lush Tirumala Hills, renowned for its Dravidian architecture and the gold-plated Ananda Nilayam vimana.",
                    "historical_significance": "Dedicated to Lord Venkateswara (an incarnation of Vishnu). Its origins date back before the 5th century, with immense contributions from the Chola, Pandya, and Vijayanagara empires. It is one of the most visited and richest pilgrimage centers in the world.",
                    "best_time_to_visit": "September to February",
                    "entry_fee": "Free for Sarva Darshan (Special Entry Darshan: ₹300)",
                    "timings": "2:30 AM – 1:30 AM (Varies heavily by day, rituals, and crowd)",
                    "location_map_url": "https://maps.google.com/?q=Tirumala+Venkateswara+Temple",
                    "nearby_attractions": "Silathoranam\nSri Padmavathi Ammavari Temple\nKapila Theertham",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Silathoranam",
                    "categories": ["nature", "geological_wonder"],
                    "description": "A rare natural rock arch formation located in the Tirumala Hills, seamlessly blending geological wonder with local mythology.",
                    "historical_significance": "Declared a National Geo-heritage Monument, this natural bridge is believed to be millions of years old. In local mythology, it is said to be the spot where Lord Venkateswara entered the Tirumala Hills.",
                    "best_time_to_visit": "September to February",
                    "entry_fee": "Free entry",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Silathoranam+Tirupati",
                    "nearby_attractions": "Sri Venkateswara Temple\nChakra Teertham\nSrivari Padalu",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Vijayawada",
            "places": [
                {
                    "name": "Undavalli Caves",
                    "categories": ["heritage", "caves", "architecture"],
                    "description": "A fascinating four-story monolithic rock-cut cave complex featuring intricate pillars and a massive reclining statue of Lord Vishnu sculpted from a single block of granite.",
                    "historical_significance": "Carved out of solid sandstone in the 4th to 5th centuries AD, initially associated with the Vishnukundina kings. They showcase a brilliant blend of Buddhist and Hindu architectural styles.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹25 (Indians), ₹300 (Foreigners)",
                    "timings": "9:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Undavalli+Caves",
                    "nearby_attractions": "Prakasam Barrage\nKanaka Durga Temple\nBhavani Island",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Kanaka Durga Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "A famous Hindu temple dedicated to Goddess Durga, majestically situated on the Indrakeeladri hill overlooking the Krishna River.",
                    "historical_significance": "According to legends, this is the spot where Arjuna obtained the Pasupatha astra after penance, and where Goddess Durga defeated the demon Mahishasura. It is highly revered during the Dasara festival.",
                    "best_time_to_visit": "October to March (Especially during Navaratri)",
                    "entry_fee": "Free for Dharma Darshanam (Special darshan tickets available)",
                    "timings": "4:00 AM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Kanaka+Durga+Temple+Vijayawada",
                    "nearby_attractions": "Prakasam Barrage\nBhavani Island\nUndavalli Caves",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}