DATA = {
    "state": {
        "name": "Assam",
        "capital": "Dispur",
        "description": "The gateway to Northeast India — famous for the mighty Brahmaputra river, sprawling tea estates, vibrant Bihu culture, and the rare one-horned rhinoceros.",
    },
    "cities": [
        {
            "name": "Guwahati",
            "places": [
                {
                    "name": "Kamakhya Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "A highly revered Hindu temple dedicated to the mother goddess Kamakhya, situated majestically on the Nilachal Hill.",
                    "historical_significance": "One of the oldest of the 51 Shakti Pithas. The current structural temple, rebuilt in 1565 by Chilarai of the Koch dynasty, features a unique hemispherical dome on a cruciform base known as the Nilachal type of architecture.",
                    "best_time_to_visit": "October to April (June for the famous Ambubachi Mela)",
                    "entry_fee": "Free for General Darshan (Special/VIP Darshan: ₹500)",
                    "timings": "5:30 AM – 1:00 PM & 2:30 PM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Kamakhya+Temple+Guwahati",
                    "nearby_attractions": "Umananda Temple\nAssam State Museum\nBrahmaputra Heritage Centre",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Umananda Temple",
                    "categories": ["heritage", "nature", "river_island"],
                    "description": "A 17th-century Shiva temple located on Peacock Island, the smallest inhabited riverine island in the world, right in the middle of the Brahmaputra River.",
                    "historical_significance": "Built by the Ahom King Gadadhar Singha in 1694. The island was named Peacock Island by a British officer due to its distinctive shape.",
                    "best_time_to_visit": "October to April",
                    "entry_fee": "Free entry (Ferry ride: ₹20 - ₹100 approx.)",
                    "timings": "5:30 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Umananda+Island+Guwahati",
                    "nearby_attractions": "Kamakhya Temple\nFancy Bazaar\nBrahmaputra Ropeway",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Kaziranga",
            "places": [
                {
                    "name": "Kaziranga National Park",
                    "categories": ["nature", "wildlife", "unesco"],
                    "description": "A vast expanse of tall elephant grass, marshland, and dense tropical moist broadleaf forests, crisscrossed by four major rivers including the Brahmaputra.",
                    "historical_significance": "A UNESCO World Heritage Site hosting two-thirds of the world's great one-horned rhinoceroses. The park celebrated its centenary in 2005 after being established as a reserve forest in 1905 on the recommendation of Mary Curzon.",
                    "best_time_to_visit": "November to April (Closed from May to October due to monsoon floods)",
                    "entry_fee": "₹100 (Indians), ₹650 (Foreigners) + Jeep/Elephant Safari charges",
                    "timings": "Open 24 hours (Safaris: 7:30 AM – 10:00 AM & 1:30 PM – 3:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Kaziranga+National+Park",
                    "nearby_attractions": "Kaziranga Orchid Park\nHollongapar Gibbon Sanctuary\nKakochang Waterfalls",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Kaziranga Orchid and Biodiversity Park",
                    "categories": ["nature", "gardens", "culture"],
                    "description": "The largest orchid park in India, sprawling over 6 acres and housing over 600 species of wild orchids, medicinal plants, and traditional Assam cultural showcases.",
                    "historical_significance": "Established to preserve the rich botanical heritage of the Northeast and promote eco-tourism alongside authentic local Assamese folk culture and cuisine.",
                    "best_time_to_visit": "October to April (Orchids bloom best in April/May)",
                    "entry_fee": "₹250 approx.",
                    "timings": "8:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Kaziranga+Orchid+Park",
                    "nearby_attractions": "Kaziranga National Park\nKakochang Waterfalls\nLocal Tea Estates",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Majuli",
            "places": [
                {
                    "name": "Majuli River Island",
                    "categories": ["heritage", "culture", "river_island"],
                    "description": "The world's largest river island, known for its lush green, pollution-free environment, breathtaking sunsets, and vibrant Neo-Vaishnavite culture.",
                    "historical_significance": "The cultural capital of Assam for over 500 years. It was the hub of the Neo-Vaishnavite movement initiated by the revered 15th-century saint and social reformer Srimanta Sankardev.",
                    "best_time_to_visit": "October to March (November for the vibrant Raas Mahotsav festival)",
                    "entry_fee": "Free to explore (Ferry to the island costs ₹15-₹30)",
                    "timings": "Open 24 hours (Ferries operate from 7:00 AM to 4:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Majuli+Island+Assam",
                    "nearby_attractions": "Kamalabari Satra\nDakhinpat Satra\nAuniati Satra",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}