DATA = {
    "state": {
        "name": "Bihar",
        "capital": "Patna",
        "description": "The land of ancient enlightenment and learning — home to the birthplaces of religions, historic empires, and the sprawling ruins of the world's earliest universities.",
    },
    "cities": [
        {
            "name": "Bodh Gaya",
            "places": [
                {
                    "name": "Mahabodhi Temple",
                    "categories": ["heritage", "spiritual", "unesco"],
                    "description": "A magnificent ancient temple complex marking the exact location where Siddhartha Gautama attained enlightenment under the sacred Bodhi Tree.",
                    "historical_significance": "Originally built by Emperor Ashoka in the 3rd century BCE, the current soaring pyramidal structure dates back to the 5th-6th centuries CE and is a UNESCO World Heritage site.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free for general entry, ₹100 for camera photography",
                    "timings": "5:00 AM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Mahabodhi+Temple+Bodh+Gaya",
                    "nearby_attractions": "Great Buddha Statue\nThai Monastery\nDungeshwari Cave Temples",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Great Buddha Statue",
                    "categories": ["heritage", "spiritual", "monument"],
                    "description": "A towering 80-foot majestic stone and copper statue of Lord Buddha in a deep meditation pose, sitting gracefully on a lotus.",
                    "historical_significance": "Consecrated in 1989 by the 14th Dalai Lama, it was the first giant Buddha statue built in modern India, inspiring a trend of similar monumental constructions across the country.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "7:00 AM – 12:00 PM & 2:00 PM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Great+Buddha+Statue+Bodh+Gaya",
                    "nearby_attractions": "Mahabodhi Temple\nRoyal Bhutan Monastery\nSujata Stupa",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Nalanda",
            "places": [
                {
                    "name": "Nalanda Mahavihara (University Ruins)",
                    "categories": ["heritage", "ruins", "unesco"],
                    "description": "The sprawling red-brick ruins of one of the world's most ancient and revered residential universities, featuring massive stupas, viharas, and monastic classrooms.",
                    "historical_significance": "Founded in the 5th century CE during the Gupta Empire, it attracted scholars from across Asia for over 700 years until its tragic destruction in the 12th century.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Nalanda+University+Ruins",
                    "nearby_attractions": "Nalanda Archaeological Museum\nXuanzang Memorial Hall\nVishwa Shanti Stupa (Rajgir)",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Xuanzang Memorial Hall",
                    "categories": ["heritage", "museum", "memorial"],
                    "description": "A beautifully designed modern architectural hall blending Indian and Chinese styles, honoring the great Chinese monk, scholar, and traveler.",
                    "historical_significance": "Built to commemorate Xuanzang (Hiuen Tsang), who spent several years studying and teaching at Nalanda in the 7th century, and whose writings preserved vital historical records of ancient India.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹10",
                    "timings": "9:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Xuanzang+Memorial+Hall+Nalanda",
                    "nearby_attractions": "Nalanda Mahavihara\nNalanda Multimedia Museum\nBlack Buddha Temple",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Patna",
            "places": [
                {
                    "name": "Takht Sri Patna Sahib",
                    "categories": ["heritage", "spiritual", "gurdwara"],
                    "description": "A magnificent white-marble Gurdwara and one of the five Takhts (holy seats of authority) of Sikhism, situated in the bustling heart of Old Patna.",
                    "historical_significance": "Built by Maharaja Ranjit Singh to commemorate the birthplace of the tenth Sikh Guru, Guru Gobind Singh Ji, who was born here in 1666.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "4:00 AM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Takht+Sri+Patna+Sahib",
                    "nearby_attractions": "Golghar\nPatna Museum\nMahavir Mandir",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Golghar",
                    "categories": ["heritage", "monument"],
                    "description": "A distinctive, massive beehive-shaped pillarless granary featuring a dual spiral staircase that leads to a panoramic view of the city and the River Ganges.",
                    "historical_significance": "Designed in 1786 by Captain John Garstin of the British East India Company. Its purpose was to store massive amounts of grain to prevent future famines after the devastating Bengal famine of 1770.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "9:30 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Golghar+Patna",
                    "nearby_attractions": "Patna Museum\nGandhi Maidan\nBihar Museum",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}