DATA = {
    "state": {
        "name": "Delhi",
        "capital": "New Delhi",
        "is_union_territory": True,
        "description": "The historical and political heart of India, offering a striking blend of ancient Mughal monuments, colonial-era architecture, and vibrant street markets.",
    },
    "cities": [
        {
            "name": "Old Delhi",
            "places": [
                {
                    "name": "Red Fort (Lal Qila)",
                    "categories": ["heritage", "fort", "unesco"],
                    "description": "A massive 17th-century fortification made of red sandstone, featuring majestic gates, palaces, and historic halls like Diwan-i-Aam and Diwan-i-Khas.",
                    "historical_significance": "Built between 1639 and 1648 by Mughal Emperor Shah Jahan when he shifted his capital from Agra to Delhi; it served as the main residence of the Mughal emperors for nearly 200 years.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹35 (Indians), ₹550 (Foreigners)",
                    "timings": "9:30 AM – 4:30 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Red+Fort+Delhi",
                    "nearby_attractions": "Jama Masjid\nChandni Chowk\nRaj Ghat",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Jama Masjid",
                    "categories": ["heritage", "mosque"],
                    "description": "One of the largest mosques in India, boasting three great gates, four towers, and two 40-meter-high minarets constructed of alternating vertical strips of red sandstone and white marble.",
                    "historical_significance": "Commissioned by Shah Jahan and completed in 1656, it was originally named Masjid-i-Jehan-Numa, meaning 'the mosque that reflects the world'.",
                    "best_time_to_visit": "October to March (Avoid prayer times on Fridays)",
                    "entry_fee": "Free entry (Camera fee ₹300)",
                    "timings": "7:00 AM – 12:00 PM & 1:30 PM – 6:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Jama+Masjid+Delhi",
                    "nearby_attractions": "Red Fort\nChandni Chowk\nKhari Baoli Spice Market",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "New Delhi",
            "places": [
                {
                    "name": "India Gate",
                    "categories": ["heritage", "monument", "landmark"],
                    "description": "A towering 42-meter tall war memorial arch standing at the eastern edge of the ceremonial axis of New Delhi, beautifully illuminated at night.",
                    "historical_significance": "Designed by Sir Edwin Lutyens and completed in 1931 to commemorate the 70,000 soldiers of the British Indian Army who died in World War I.",
                    "best_time_to_visit": "October to March (Best visited in the evening)",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours",
                    "location_map_url": "https://maps.google.com/?q=India+Gate+Delhi",
                    "nearby_attractions": "National War Memorial\nRashtrapati Bhavan\nNational Museum",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "South Delhi",
            "places": [
                {
                    "name": "Qutub Minar",
                    "categories": ["heritage", "monument", "unesco"],
                    "description": "A soaring, 72.5-meter tall five-story victory tower made of red sandstone and marble, covered with intricate carvings and verses from the Quran.",
                    "historical_significance": "Founded in 1199 AD by Qutb-ud-din Aibak and completed by his successor Iltutmish; it marks the beginning of Muslim rule in India and is a masterpiece of Indo-Islamic architecture.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹35 (Indians), ₹550 (Foreigners)",
                    "timings": "7:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Qutub+Minar+Delhi",
                    "nearby_attractions": "Mehrauli Archaeological Park\nIron Pillar\nAlai Darwaza",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Humayun's Tomb",
                    "categories": ["heritage", "monument", "unesco"],
                    "description": "A magnificent garden-tomb featuring red sandstone structures with striking white marble borders and classic Persian-style Charbagh gardens.",
                    "historical_significance": "Commissioned in 1569 by Humayun's first wife, Empress Bega Begum. It was the first substantial example of Mughal architecture in India and later inspired the Taj Mahal.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Humayuns+Tomb+Delhi",
                    "nearby_attractions": "Sunder Nursery\nHazrat Nizamuddin Dargah\nPurana Qila",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}