DATA = {
    "state": {
        "name": "Gujarat",
        "capital": "Gandhinagar",
        "description": "A vibrant western state known for its rich mercantile history, the world's tallest statue, unique white salt deserts, and the sole home of Asiatic lions.",
    },
    "cities": [
        {
            "name": "Ahmedabad",
            "places": [
                {
                    "name": "Sabarmati Ashram",
                    "categories": ["heritage", "museum"],
                    "description": "A serene ashram on the tranquil banks of the Sabarmati River that served as one of the main nerve centers of the Indian freedom struggle.",
                    "historical_significance": "Established by Mahatma Gandhi in 1917, it was his home for over a decade and the starting point of the historic Dandi March (Salt Satyagraha) in 1930.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "8:30 AM – 6:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Sabarmati+Ashram+Ahmedabad",
                    "nearby_attractions": "Adalaj Stepwell\nKankaria Lake\nSidi Saiyyed Mosque",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Adalaj Stepwell",
                    "categories": ["heritage", "architecture"],
                    "description": "A breathtaking five-story deep stepwell featuring intricate Islamic floral patterns seamlessly blended with Hindu and Jain mythological symbolism.",
                    "historical_significance": "Built in 1498 by Queen Rudabai in memory of her husband, Rana Veer Singh, to provide water and a cool resting refuge to weary travelers and caravans.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Adalaj+Stepwell+Ahmedabad",
                    "nearby_attractions": "Akshardham Temple\nSabarmati Ashram\nThol Bird Sanctuary",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Kevadia (Ektanagar)",
            "places": [
                {
                    "name": "Statue of Unity",
                    "categories": ["monument", "landmark", "modern"],
                    "description": "A colossal 182-meter (597 ft) bronze-clad statue standing majestically on an island in the Narmada River, making it the tallest statue in the world.",
                    "historical_significance": "Inaugurated in 2018 to honor Sardar Vallabhbhai Patel, the 'Iron Man of India,' who successfully integrated over 560 princely states into the modern Republic of India.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹150 (Basic Entry), ₹380 (Viewing Gallery)",
                    "timings": "8:00 AM – 6:00 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Statue+of+Unity+Gujarat",
                    "nearby_attractions": "Sardar Sarovar Dam\nValley of Flowers\nJungle Safari",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Sardar Sarovar Dam",
                    "categories": ["nature", "engineering"],
                    "description": "One of the world's largest concrete gravity dams, offering spectacular views of the Narmada river and the surrounding lush Vindhya and Satpura mountain ranges.",
                    "historical_significance": "A massive engineering feat whose foundation was laid by Prime Minister Jawaharlal Nehru in 1961, bringing vital irrigation and hydroelectric power to multiple states.",
                    "best_time_to_visit": "August to October (During and post-monsoon for full water levels)",
                    "entry_fee": "Included in Statue of Unity entry",
                    "timings": "8:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Sardar+Sarovar+Dam+Gujarat",
                    "nearby_attractions": "Statue of Unity\nZarwani Waterfall\nCactus Garden",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Somnath",
            "places": [
                {
                    "name": "Somnath Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "An imposing Chalukya-style temple situated right on the shores of the Arabian Sea, renowned for its intricate carvings and deeply spiritual atmosphere.",
                    "historical_significance": "Revered as the first among the twelve Jyotirlinga shrines of Shiva. Known as 'The Shrine Eternal,' it was repeatedly destroyed by invaders over centuries and rebuilt each time; the current structure was completed in 1951.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "6:00 AM – 10:00 PM (Light and Sound show 8:00 PM - 9:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Somnath+Temple+Gujarat",
                    "nearby_attractions": "Bhalka Tirth\nTriveni Sangam\nSomnath Beach",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}