DATA = {
    "state": {
        "name": "Karnataka",
        "capital": "Bengaluru",
        "description": "A diverse state offering a dynamic mix of modern tech hubs, ancient UNESCO ruins, lush Western Ghats, and opulent royal palaces.",
    },
    "cities": [
        {
            "name": "Bengaluru",
            "places": [
                {
                    "name": "Bangalore Palace",
                    "categories": ["heritage", "palace"],
                    "description": "A magnificent Tudor Revival-style palace featuring fortified towers, gothic windows, exquisite wood carvings, and Victorian-era furniture.",
                    "historical_significance": "Built in 1878 by Maharaja Chamarajendra Wadiyar X, the architecture was heavily inspired by England's Windsor Castle.",
                    "best_time_to_visit": "September to February",
                    "entry_fee": "₹230 (Indians), ₹460 (Foreigners)",
                    "timings": "10:00 AM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Bangalore+Palace+Bengaluru",
                    "nearby_attractions": "Cubbon Park\nNational Gallery of Modern Art\nVidhana Soudha",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Lalbagh Botanical Garden",
                    "categories": ["nature", "gardens"],
                    "description": "A 240-acre haven holding India's largest collection of tropical plants, famous for its London Crystal Palace-inspired glasshouse.",
                    "historical_significance": "Originally commissioned in 1760 by Hyder Ali, the ruler of Mysore, and later completed by his son Tipu Sultan.",
                    "best_time_to_visit": "September to February (Especially during the Republic Day and Independence Day flower shows)",
                    "entry_fee": "₹30 (Adults), Free for children under 12",
                    "timings": "6:00 AM – 7:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Lalbagh+Botanical+Garden+Bengaluru",
                    "nearby_attractions": "Bull Temple\nTipu Sultan's Summer Palace\nCubbon Park",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Hampi",
            "places": [
                {
                    "name": "Vittala Temple",
                    "categories": ["heritage", "temple", "unesco"],
                    "description": "An architectural masterpiece renowned for its iconic stone chariot and fascinating musical pillars that emit musical notes when tapped.",
                    "historical_significance": "Built in the 15th century during the reign of King Devaraya II, it represents the highest point of Vijayanagara art and architecture.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "8:30 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Vittala+Temple+Hampi",
                    "nearby_attractions": "Virupaksha Temple\nLotus Mahal\nElephant Stables",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Virupaksha Temple",
                    "categories": ["heritage", "temple", "unesco"],
                    "description": "The main center of pilgrimage at Hampi, featuring a towering 9-tiered gopuram and intricate stone carvings dedicated to Lord Shiva.",
                    "historical_significance": "One of the oldest functioning temples in India, originating in the 7th century and massively expanded by the Vijayanagara Empire.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (₹5 for shoe keeping)",
                    "timings": "6:00 AM – 1:00 PM & 5:00 PM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Virupaksha+Temple+Hampi",
                    "nearby_attractions": "Hemakuta Hill Temples\nMatanga Hill\nHampi Bazaar",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Mysuru",
            "places": [
                {
                    "name": "Mysore Palace",
                    "categories": ["heritage", "palace"],
                    "description": "An incredibly opulent Indo-Saracenic palace featuring stained glass, mirrored halls, and a dazzling exterior illuminated by nearly 100,000 bulbs on weekends.",
                    "historical_significance": "The historical seat of the Wadiyar dynasty; the current magnificent structure was commissioned in 1897 and completed in 1912 after the old wooden palace burned down.",
                    "best_time_to_visit": "October to March (Particularly during the grand Dasara festival)",
                    "entry_fee": "₹100 (Indians), ₹200 (Foreigners)",
                    "timings": "10:00 AM – 5:30 PM (Illumination on Sundays and public holidays from 7:00 PM - 7:45 PM)",
                    "location_map_url": "https://maps.google.com/?q=Mysore+Palace",
                    "nearby_attractions": "Chamundeshwari Temple\nSri Chamarajendra Zoological Gardens\nBrindavan Gardens",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Chamundeshwari Temple",
                    "categories": ["heritage", "temple"],
                    "description": "Perched atop the Chamundi Hills, this historic temple features an impressive seven-story gopuram and a massive granite statue of Nandi (the bull) on the way up.",
                    "historical_significance": "Originally built in the 12th century by the Hoysala rulers and dedicated to Goddess Durga, the patron deity of the Mysore Maharajas.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (Special darshan tickets available for ₹100 or ₹300)",
                    "timings": "7:30 AM – 2:00 PM, 3:30 PM – 6:00 PM, 7:30 PM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Chamundeshwari+Temple+Mysuru",
                    "nearby_attractions": "Mysore Palace\nNandi Statue\nKaranji Lake",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}