DATA = {
    "state": {
        "name": "Kerala",
        "capital": "Thiruvananthapuram",
        "description": "God's Own Country — famous for its serene backwaters, rolling tea estates, spice plantations, and vibrant cultural heritage.",
    },
    "cities": [
        {
            "name": "Kochi",
            "places": [
                {
                    "name": "Mattancherry Palace",
                    "categories": ["heritage", "palace"],
                    "description": "Also known as the Dutch Palace, it features spacious long halls, a central courtyard, and an extensive collection of Kerala murals depicting Hindu temple art.",
                    "historical_significance": "Built by the Portuguese in 1555 and gifted to King Veera Kerala Verma, it was later renovated by the Dutch.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹2 per head",
                    "timings": "9:45 AM – 1:00 PM & 2:00 PM – 4:45 PM (Closed Fridays and Saturdays)",
                    "location_map_url": "https://maps.google.com/?q=Mattancherry+Palace+Kochi",
                    "nearby_attractions": "Paradesi Synagogue\nJew Town\nChinese Fishing Nets",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Chinese Fishing Nets",
                    "categories": ["heritage", "iconic", "coastal"],
                    "description": "Iconic, massive cantilevered fishing nets permanently installed on bamboo and teak poles along the Fort Kochi coastline.",
                    "historical_significance": "Believed to have been introduced by Chinese explorer Zheng He in the 14th century, they remain a symbol of Kochi's ancient maritime trade.",
                    "best_time_to_visit": "October to March (Best seen during sunset)",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours (Fishing activity is best seen early morning or evening)",
                    "location_map_url": "https://maps.google.com/?q=Chinese+Fishing+Nets+Kochi",
                    "nearby_attractions": "Fort Kochi Beach\nSt. Francis Church\nVasco da Gama Square",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Munnar",
            "places": [
                {
                    "name": "Eravikulam National Park",
                    "categories": ["nature", "wildlife", "national_park"],
                    "description": "A 97 sq. km park of green hills and meadows, famous for the rare blooming of Neelakurinji flowers and rolling tea garden vistas.",
                    "historical_significance": "A crucial sanctuary dedicated to the conservation of the endangered Nilgiri Tahr, a mountain goat endemic to the Western Ghats.",
                    "best_time_to_visit": "September to March (Closed in February and March for the Nilgiri Tahr calving season)",
                    "entry_fee": "₹200 (Indian Adults), ₹95 (Children), ₹500 (Foreigners)",
                    "timings": "7:30 AM – 4:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Eravikulam+National+Park+Munnar",
                    "nearby_attractions": "Anamudi Peak\nMattupetty Dam\nTea Museum",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Mattupetty Dam",
                    "categories": ["nature", "leisure", "lakes"],
                    "description": "A gravity dam surrounded by lush green valleys and tea plantations, providing a peaceful boating experience and opportunities for bird watching.",
                    "historical_significance": "Constructed in the 1940s as part of the Pallivasal Hydro-electric project to conserve water for power generation.",
                    "best_time_to_visit": "September to March",
                    "entry_fee": "₹10 (Boating fees extra, approx. ₹500 - ₹700 for a boat)",
                    "timings": "9:30 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Mattupetty+Dam+Munnar",
                    "nearby_attractions": "Echo Point\nKundala Lake\nTop Station",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Alappuzha",
            "places": [
                {
                    "name": "Vembanad Lake Backwaters",
                    "categories": ["nature", "leisure", "backwaters"],
                    "description": "India's longest lake and the heart of Kerala's backwater tourism, featuring a mesmerizing labyrinth of canals, lagoons, and floating houseboats (Kettuvalloms).",
                    "historical_significance": "The lake is central to the socio-economic life of Kuttanad, the 'Rice Bowl of Kerala', known for its unique below-sea-level biosaline farming.",
                    "best_time_to_visit": "November to February",
                    "entry_fee": "Free to visit (Houseboats and Shikara rides are charged separately)",
                    "timings": "Open 24 hours (Cruises typically operate from 8:00 AM to 5:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Vembanad+Lake+Alappuzha",
                    "nearby_attractions": "Kumarakom Bird Sanctuary\nPathiramanal Island\nAmbalapuzha Sree Krishna Temple",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Alappuzha Beach",
                    "categories": ["nature", "beach"],
                    "description": "A scenic beach on the Arabian Sea featuring golden sand, palm-lined shores, an old lighthouse, and a historic 137-year-old wooden pier extending into the sea.",
                    "historical_significance": "The beach and its decaying pier stand as a reminder of Alappuzha's bustling maritime past as a major colonial port city known as the 'Venice of the East'.",
                    "best_time_to_visit": "November to February",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours (Best visited during sunrise or sunset)",
                    "location_map_url": "https://maps.google.com/?q=Alappuzha+Beach",
                    "nearby_attractions": "Vijaya Beach Park\nAlappuzha Lighthouse\nRevi Karunakaran Memorial Museum",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}