DATA = {
    "state": {
        "name": "Madhya Pradesh",
        "capital": "Bhopal",
        "description": "The 'Heart of India' — celebrated for its sprawling wildlife reserves, ancient Buddhist stupas, intricately carved temples, and majestic hilltop forts.",
    },
    "cities": [
        {
            "name": "Bhopal",
            "places": [
                {
                    "name": "Bhimbetka Rock Shelters",
                    "categories": ["heritage", "caves", "unesco"],
                    "description": "A massive complex of natural rock shelters featuring vivid prehistoric cave paintings depicting animals, hunting, and early human life.",
                    "historical_significance": "A UNESCO World Heritage site with evidence of human settlement from the Paleolithic and Mesolithic periods; some paintings are over 30,000 years old.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹25 (Indians), ₹500 (Foreigners)",
                    "timings": "7:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Bhimbetka+Rock+Shelters+Madhya+Pradesh",
                    "nearby_attractions": "Bhojpur Temple\nUpper Lake\nSanchi Stupa",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Upper Lake (Bhojtal)",
                    "categories": ["nature", "lakes", "leisure"],
                    "description": "One of the oldest man-made lakes in India, offering picturesque sunrise views, boat clubs, and a tranquil escape from the city bustles.",
                    "historical_significance": "Believed to have been constructed in the 11th century by the Paramara King Bhoj to cure a skin disease and provide water to the region.",
                    "best_time_to_visit": "August to March",
                    "entry_fee": "Free entry (Boating: ₹100 - ₹250 approx.)",
                    "timings": "6:00 AM – 7:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Upper+Lake+Bhopal",
                    "nearby_attractions": "Van Vihar National Park\nTaj-ul-Masajid\nMadhya Pradesh Tribal Museum",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Khajuraho",
            "places": [
                {
                    "name": "Khajuraho Group of Monuments",
                    "categories": ["heritage", "temple", "unesco"],
                    "description": "An awe-inspiring complex of Hindu and Jain temples renowned globally for their Nagara-style architectural symbolism and intricate erotic sculptures.",
                    "historical_significance": "Built between 950 and 1050 CE by the Chandela dynasty. Out of the original 85 temples, only 25 have survived the test of time.",
                    "best_time_to_visit": "October to March (Especially during the Khajuraho Dance Festival in February)",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "8:00 AM – 6:00 PM (Light & Sound show in the evening)",
                    "location_map_url": "https://maps.google.com/?q=Khajuraho+Group+of+Monuments",
                    "nearby_attractions": "Kandariya Mahadeva Temple\nPanna National Park\nRaneh Falls",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Gwalior",
            "places": [
                {
                    "name": "Gwalior Fort",
                    "categories": ["heritage", "fort", "landmark"],
                    "description": "An imposing hill fort boasting massive defensive walls, stunning blue-tiled palaces like the Man Mandir, and ancient Jain rock sculptures.",
                    "historical_significance": "Existed since at least the 10th century and ruled by various dynasties. Mughal Emperor Babur famously described it as 'the pearl amongst fortresses in India'.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹75 (Indians), ₹250 (Foreigners)",
                    "timings": "8:00 AM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Gwalior+Fort",
                    "nearby_attractions": "Jai Vilas Palace\nSasbahu Temple\nGujari Mahal Archaeological Museum",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Jai Vilas Palace",
                    "categories": ["heritage", "palace", "museum"],
                    "description": "A lavish 19th-century palace blending Tuscan, Italian, and Corinthian architectural styles, famously housing a pair of the world's largest chandeliers.",
                    "historical_significance": "Constructed in 1874 by Jayajirao Scindia to welcome King Edward VII; it remains the residence of the erstwhile royal Scindia family.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹300 (Indians), ₹850 (Foreigners)",
                    "timings": "10:00 AM – 4:30 PM (Closed on Wednesdays)",
                    "location_map_url": "https://maps.google.com/?q=Jai+Vilas+Palace+Gwalior",
                    "nearby_attractions": "Gwalior Fort\nTansen Tomb\nSun Temple Gwalior",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}