DATA = {
    "state": {
        "name": "Maharashtra",
        "capital": "Mumbai",
        "description": "A vibrant state blending historic forts, ancient UNESCO rock-cut caves, scenic Western Ghats, and bustling coastal cities.",
    },
    "cities": [
        {
            "name": "Mumbai",
            "places": [
                {
                    "name": "Gateway of India",
                    "categories": ["heritage", "monument"],
                    "description": "An iconic arch-monument built of yellow basalt and concrete, overlooking the Arabian Sea.",
                    "historical_significance": "Erected to commemorate the landing of King-Emperor George V and Queen-Empress Mary at Apollo Bunder in 1911, it later became the point from where the last British troops left India in 1948.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours",
                    "location_map_url": "https://maps.google.com/?q=Gateway+of+India+Mumbai",
                    "nearby_attractions": "Taj Mahal Palace\nColaba Causeway\nMarine Drive",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Elephanta Caves",
                    "categories": ["heritage", "caves", "unesco"],
                    "description": "A network of sculpted cave temples on Elephanta Island, predominantly dedicated to the Hindu god Shiva.",
                    "historical_significance": "Dating back to the 5th-7th centuries, these caves represent the pinnacle of rock-cut architecture and sculptural art in medieval India, with the 20-foot Trimurti (three-headed Shiva) as its masterpiece.",
                    "best_time_to_visit": "November to February",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "9:30 AM – 5:30 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Elephanta+Caves+Mumbai",
                    "nearby_attractions": "Gateway of India (Ferry starting point)\nChhatrapati Shivaji Maharaj Vastu Sangrahalaya",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Pune",
            "places": [
                {
                    "name": "Shaniwar Wada",
                    "categories": ["heritage", "fort"],
                    "description": "A historic fortification that once featured sprawling gardens, fountains, and courtyards, though mostly ruins remain today after an unexplained 1828 fire.",
                    "historical_significance": "Built in 1732, it was the great seat of the Peshwas of the Maratha Empire until control was lost to the British East India Company in 1818.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹25 (Indians), ₹300 (Foreigners)",
                    "timings": "8:00 AM – 6:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Shaniwar+Wada+Pune",
                    "nearby_attractions": "Dagdusheth Halwai Ganpati Temple\nRaja Dinkar Kelkar Museum\nVishrambaug Wada",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Aga Khan Palace",
                    "categories": ["heritage", "monument"],
                    "description": "A majestic palace featuring Italian arches and expansive lawns, intrinsically linked to the Indian freedom movement.",
                    "historical_significance": "Built in 1892, it served as a prison for Mahatma Gandhi, his wife Kasturba Gandhi, and Sarojini Naidu during the 1942 Quit India Movement.",
                    "best_time_to_visit": "July to March",
                    "entry_fee": "₹25 (Indians), ₹300 (Foreigners)",
                    "timings": "9:00 AM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Aga+Khan+Palace+Pune",
                    "nearby_attractions": "Osho Ashram\nPataleshwar Cave Temple\nBund Garden",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Chhatrapati Sambhajinagar",
            "places": [
                {
                    "name": "Ajanta Caves",
                    "categories": ["heritage", "caves", "unesco"],
                    "description": "Approximately 30 rock-cut Buddhist cave monuments known for their exquisite ancient mural paintings and sculptures.",
                    "historical_significance": "Dating from the 2nd century BCE to about 480 CE, these caves showcase the pinnacle of ancient Indian art and illustrate the lives of the Buddha.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Ajanta+Caves+Maharashtra",
                    "nearby_attractions": "Ellora Caves\nDaulatabad Fort\nBibi Ka Maqbara",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Ellora Caves",
                    "categories": ["heritage", "caves", "unesco"],
                    "description": "A spectacular site featuring over 100 rock-cut caves, including the world's largest monolithic rock excavation, the Kailasa temple.",
                    "historical_significance": "Constructed between 600 CE and 1000 CE, these monuments represent a remarkable harmony of Hindu, Buddhist, and Jain faiths sharing a single site.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "6:00 AM – 6:00 PM (Closed on Tuesdays)",
                    "location_map_url": "https://maps.google.com/?q=Ellora+Caves+Maharashtra",
                    "nearby_attractions": "Grishneshwar Temple\nBibi Ka Maqbara\nDaulatabad Fort",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}