DATA = {
    "state": {
        "name": "Meghalaya",
        "capital": "Shillong",
        "description": "Known as the 'Abode of Clouds' — famous for its mystical living root bridges, cascading waterfalls, crystal-clear rivers, and lush green valleys.",
    },
    "cities": [
        {
            "name": "Shillong",
            "places": [
                {
                    "name": "Umiam Lake",
                    "categories": ["nature", "lakes", "leisure"],
                    "description": "A mesmerizing man-made reservoir surrounded by the lush green East Khasi Hills, offering water sports, boating, and stunning sunset views.",
                    "historical_significance": "Formed in the early 1960s by damming the Umiam River as part of Northeast India's first hydel power project.",
                    "best_time_to_visit": "October to May",
                    "entry_fee": "Free entry (Boating: ₹100 - ₹200 approx.)",
                    "timings": "9:00 AM – 5:00 PM (for water sports)",
                    "location_map_url": "https://maps.google.com/?q=Umiam+Lake+Shillong",
                    "nearby_attractions": "Elephant Falls\nDon Bosco Museum\nShillong Peak",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Don Bosco Museum",
                    "categories": ["heritage", "museum", "culture"],
                    "description": "A massive seven-story hexagonal museum showcasing the rich and diverse indigenous cultures, art, and history of all Northeast Indian states.",
                    "historical_significance": "It stands as Asia's largest museum of indigenous cultures, preserving the heritage, traditional attire, and weapons of various tribal communities of the region.",
                    "best_time_to_visit": "Year-round",
                    "entry_fee": "₹100 (Indians), ₹200 (Foreigners)",
                    "timings": "9:00 AM – 5:30 PM (Closed on Sundays)",
                    "location_map_url": "https://maps.google.com/?q=Don+Bosco+Museum+Shillong",
                    "nearby_attractions": "Ward's Lake\nPolice Bazar\nGolf Links",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Cherrapunji (Sohra)",
            "places": [
                {
                    "name": "Umshiang Double Decker Living Root Bridge",
                    "categories": ["nature", "adventure", "eco_tourism"],
                    "description": "An extraordinary feat of indigenous bio-engineering, featuring two tiers of bridges naturally woven from the thick roots of rubber trees over a river.",
                    "historical_significance": "Grown over centuries by the local Khasi tribes to cross swollen rivers during heavy monsoons, representing a perfect harmony between humans and nature.",
                    "best_time_to_visit": "October to April (Requires a rigorous 3,000-step trek down to Nongriat village)",
                    "entry_fee": "₹20 (Camera fees extra)",
                    "timings": "6:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Double+Decker+Living+Root+Bridge+Nongriat",
                    "nearby_attractions": "Nohkalikai Falls\nMawsmai Cave\nRainbow Falls",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Nohkalikai Falls",
                    "categories": ["nature", "waterfall"],
                    "description": "The tallest plunge waterfall in India, spectacularly dropping 340 meters from a lush green plateau into a stunning turquoise pool below.",
                    "historical_significance": "The name translates to 'Jump of Ka Likai' in the local Khasi language, tied to a tragic local legend of a grieving mother who leaped from the cliff.",
                    "best_time_to_visit": "September to November (Post-monsoon for the best flow without heavy fog)",
                    "entry_fee": "₹20 per person",
                    "timings": "9:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Nohkalikai+Falls+Cherrapunji",
                    "nearby_attractions": "Seven Sisters Falls\nMawsmai Cave\nEco Park",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Dawki",
            "places": [
                {
                    "name": "Umngot River",
                    "categories": ["nature", "river", "border"],
                    "description": "A spectacularly crystal-clear river where the water is so transparent that boats appear to be floating on thin air.",
                    "historical_significance": "Serves as a natural boundary between the Jaintia and Khasi hills, and acts as a significant trade route at the international border between India and Bangladesh.",
                    "best_time_to_visit": "November to April (Water is clearest during winter)",
                    "entry_fee": "Free entry (Boating: ₹500 - ₹800 per boat)",
                    "timings": "8:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Umngot+River+Dawki",
                    "nearby_attractions": "Mawlynnong Village\nKrang Suri Falls\nJaflong Zero Point",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}