DATA = {
    "state": {
        "name": "Odisha",
        "capital": "Bhubaneswar",
        "description": "India's best-kept secret — a coastal state renowned for its majestic Kalinga architecture, ancient tribal cultures, golden beaches, and the spectacular Rath Yatra.",
    },
    "cities": [
        {
            "name": "Bhubaneswar",
            "places": [
                {
                    "name": "Lingaraja Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "A breathtaking 11th-century temple dedicated to Lord Shiva (Harihara), standing at 180 feet tall and serving as the focal point of the 'Temple City'.",
                    "historical_significance": "A masterpiece of Kalinga architecture built by the Somavamsi dynasty. It is one of the oldest and largest temples in Bhubaneswar.",
                    "best_time_to_visit": "October to March (Particularly vibrant during Shivaratri)",
                    "entry_fee": "Free entry (Only Hindus are allowed inside; foreigners can view from a viewing platform)",
                    "timings": "6:00 AM – 12:30 PM & 3:30 PM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Lingaraja+Temple+Bhubaneswar",
                    "nearby_attractions": "Mukteshwara Temple\nBindu Sagar Lake\nRajarani Temple",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Udayagiri and Khandagiri Caves",
                    "categories": ["heritage", "caves", "architecture"],
                    "description": "A complex of partly natural and partly artificial caves carved into two adjacent hills, adorned with ornate rock-cut sculptures and inscriptions.",
                    "historical_significance": "Excavated in the 1st century BCE during the reign of King Kharavela to serve as residential blocks for Jain monks.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹25 (Indians), ₹300 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Udayagiri+and+Khandagiri+Caves",
                    "nearby_attractions": "Dhauli Shanti Stupa\nLingaraja Temple\nOdisha State Museum",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Puri",
            "places": [
                {
                    "name": "Jagannath Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "A magnificent sacred temple complex dedicated to Lord Jagannath, featuring an imposing 65-meter-high spire (sikhara) and an enormous traditional kitchen.",
                    "historical_significance": "Built in the 12th century by King Anantavarman Chodaganga Deva. It is one of the Char Dham pilgrimage sites and globally famous for its annual Rath Yatra (Chariot Festival).",
                    "best_time_to_visit": "October to March (June/July for Rath Yatra)",
                    "entry_fee": "Free entry (Only Hindus are allowed inside the main temple complex)",
                    "timings": "5:30 AM – 11:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Jagannath+Temple+Puri",
                    "nearby_attractions": "Puri Beach\nGundicha Temple\nChilika Lake",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Puri Beach (Golden Beach)",
                    "categories": ["nature", "beach", "leisure"],
                    "description": "A sprawling stretch of fine golden sand along the Bay of Bengal, famous for its crashing waves and intricate sand art sculptures by local artists.",
                    "historical_significance": "A historically significant coastal stretch that has hosted pilgrims for centuries who take a holy dip in the sea before visiting the Jagannath Temple. It recently earned the prestigious 'Blue Flag' certification for cleanliness.",
                    "best_time_to_visit": "October to March (Best visited at sunrise)",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours",
                    "location_map_url": "https://maps.google.com/?q=Puri+Beach+Odisha",
                    "nearby_attractions": "Jagannath Temple\nKonark Sun Temple\nRaghurajpur Artist Village",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Konark",
            "places": [
                {
                    "name": "Konark Sun Temple",
                    "categories": ["heritage", "temple", "unesco"],
                    "description": "A stunning 13th-century sun temple shaped like a colossal stone chariot with 24 intricately carved wheels, drawn by seven spirited stone horses.",
                    "historical_significance": "Built by King Narasimhadeva I of the Eastern Ganga dynasty. Designated as a UNESCO World Heritage site and renowned for its exquisite Kalinga architecture and erotic stone carvings.",
                    "best_time_to_visit": "September to March (February for the Konark Dance Festival)",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners)",
                    "timings": "6:00 AM – 8:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Konark+Sun+Temple",
                    "nearby_attractions": "Chandrabhaga Beach\nRamachandi Temple\nKuruma Buddhist Site",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}