DATA = {
    "state": {
        "name": "Punjab",
        "capital": "Chandigarh",
        "description": "The Land of Five Rivers — known for its rich Sikh heritage, golden agricultural fields, vibrant culture, and historical landmarks.",
    },
    "cities": [
        {
            "name": "Amritsar",
            "places": [
                {
                    "name": "Golden Temple (Sri Harmandir Sahib)",
                    "categories": ["heritage", "spiritual", "gurdwara"],
                    "description": "The holiest Gurdwara of Sikhism, stunningly gilded with gold and surrounded by the serene Amrit Sarovar (Pool of Nectar).",
                    "historical_significance": "Founded in 1577 by the fourth Sikh guru, Guru Ram Das. The temple was rebuilt in 1764, and its upper floors were covered in gold by Maharaja Ranjit Singh in 1830.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours",
                    "location_map_url": "https://maps.google.com/?q=Golden+Temple+Amritsar",
                    "nearby_attractions": "Jallianwala Bagh\nPartition Museum\nWagah Border",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Jallianwala Bagh",
                    "categories": ["heritage", "memorial"],
                    "description": "A historic public garden that houses a poignant memorial of national importance, bearing the bullet marks from one of India's darkest days.",
                    "historical_significance": "The site of the tragic 1919 massacre where British Indian Army soldiers opened fire on a peaceful gathering of unarmed Indians on the orders of Brigadier-General R.E.H. Dyer.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "6:30 AM – 7:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Jallianwala+Bagh+Amritsar",
                    "nearby_attractions": "Golden Temple\nPartition Museum\nDurgiana Temple",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Wagah Border",
                    "categories": ["heritage", "border", "landmark"],
                    "description": "The international border separating India and Pakistan, famous for the energetic and synchronized daily Beating Retreat border ceremony.",
                    "historical_significance": "Marks the Radcliffe Line, drawn during the 1947 partition of India. The lowering of the flags ceremony has been a daily military practice since 1959.",
                    "best_time_to_visit": "October to March (Arrive by 3:00 PM to secure a seat)",
                    "entry_fee": "Free entry",
                    "timings": "4:15 PM – 5:00 PM (Winter), 5:15 PM – 6:00 PM (Summer)",
                    "location_map_url": "https://maps.google.com/?q=Wagah+Border+Amritsar",
                    "nearby_attractions": "Pul Kanjri\nSadda Pind\nPunjab State War Heroes' Memorial",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Patiala",
            "places": [
                {
                    "name": "Qila Mubarak Complex",
                    "categories": ["heritage", "fort", "palace"],
                    "description": "An imposing 18th-century fort and palace complex featuring the Qila Androon (inner fort) with beautifully painted chambers and intricate mirror work.",
                    "historical_significance": "Built in 1763 by Baba Ala Singh, the founder of the Patiala dynasty. It represents a rare and outstanding example of traditional Sikh palace architecture.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹20 (Indians), ₹200 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Qila+Mubarak+Patiala",
                    "nearby_attractions": "Sheesh Mahal\nBaradari Gardens\nMoti Bagh Palace",
                    "is_featured": False,
                    "is_verified": True,
                },
                {
                    "name": "Sheesh Mahal",
                    "categories": ["heritage", "palace"],
                    "description": "The 'Palace of Mirrors' renowned for its extensive glass and mirror work, a suspension bridge resembling the Lakshman Jhula, and a museum housing antiquities.",
                    "historical_significance": "Built in 1847 by Maharaja Narinder Singh, the palace showcases a blend of Mughal and European architectural styles alongside Kangra and Rajput paintings.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹20 (Indians), ₹200 (Foreigners)",
                    "timings": "10:00 AM – 5:00 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Sheesh+Mahal+Patiala",
                    "nearby_attractions": "Moti Bagh Palace\nQila Mubarak\nBaradari Gardens",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Anandpur Sahib",
            "places": [
                {
                    "name": "Virasat-e-Khalsa",
                    "categories": ["heritage", "museum", "culture"],
                    "description": "A stunningly designed, ultra-modern museum complex that celebrates 500 years of Sikh history and the 300th anniversary of the birth of the Khalsa.",
                    "historical_significance": "Inaugurated in 2011 to commemorate the rich heritage of the Khalsa panth, showcasing the vision of the Sikh Gurus and their message of peace and brotherhood through interactive exhibits.",
                    "best_time_to_visit": "September to March",
                    "entry_fee": "Free entry",
                    "timings": "10:00 AM – 4:30 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Virasat-e-Khalsa+Anandpur+Sahib",
                    "nearby_attractions": "Takht Sri Keshgarh Sahib\nBhakra Nangal Dam\nNaina Devi Temple",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}