DATA = {
    "state": {
        "name": "Rajasthan",
        "capital": "Jaipur",
        "description": "The Land of Kings — renowned for grand hill forts, majestic palaces, vibrant folk culture, and golden desert landscapes.",
    },
    "cities": [
        {
            "name": "Jaipur",
            "places": [
                {
                    "name": "Amber Fort",
                    "categories": ["heritage", "fort"],
                    "description": "A magnificent hilltop fort known for its artistic Hindu-Rajput architecture, intricate mirror work in Sheesh Mahal, and sweeping views of Maota Lake.",
                    "historical_significance": "Built by Raja Man Singh I in 1592, Amber Fort served as the principal seat of the Kachwaha Rajputs before the founding of Jaipur.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹100 (Indians), ₹500 (Foreigners)",
                    "timings": "8:00 AM – 5:30 PM, 6:30 PM – 9:15 PM (Night entry)",
                    "location_map_url": "https://maps.google.com/?q=Amber+Fort+Jaipur",
                    "nearby_attractions": "Jaigarh Fort\nPanna Meena ka Kund\nJal Mahal",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Hawa Mahal",
                    "categories": ["heritage", "architecture"],
                    "description": "The iconic five-story 'Palace of Winds' built with red and pink sandstone, featuring 953 delicately carved jharokhas (windows).",
                    "historical_significance": "Constructed in 1799 by Maharaja Sawai Pratap Singh, designed so royal women could observe daily city life and street processions unobserved.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹50 (Indians), ₹200 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Hawa+Mahal+Jaipur",
                    "nearby_attractions": "City Palace Jaipur\nJantar Mantar\nBapu Bazaar",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Jantar Mantar",
                    "categories": ["heritage", "astronomy", "unesco"],
                    "description": "A UNESCO World Heritage astronomical observatory housing the world's largest stone sundial and nineteen architectural astronomical instruments.",
                    "historical_significance": "Completed in 1734 by astronomer king Maharaja Sawai Jai Singh II to compile astronomical tables and predict celestial movements.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹50 (Indians), ₹200 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Jantar+Mantar+Jaipur",
                    "nearby_attractions": "City Palace Jaipur\nHawa Mahal\nAlbert Hall Museum",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Udaipur",
            "places": [
                {
                    "name": "City Palace",
                    "categories": ["heritage", "palace"],
                    "description": "A massive lakeside palace complex built over 400 years, blending Rajasthani and Mughal architectural styles with courtyards, terraces, and mirror mosaics.",
                    "historical_significance": "Founded in 1559 by Maharana Udai Singh II as the administrative and ceremonial headquarters of the Mewar Kingdom.",
                    "best_time_to_visit": "September to March",
                    "entry_fee": "₹400 (Adults), ₹150 (Children)",
                    "timings": "9:30 AM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=City+Palace+Udaipur",
                    "nearby_attractions": "Lake Pichola\nJagdish Temple\nBagore Ki Haveli",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Lake Pichola",
                    "categories": ["nature", "lakes", "leisure"],
                    "description": "An artificial freshwater lake famous for sunset boat cruises and picturesque views of the Lake Palace, Jag Mandir, and surrounding Aravalli hills.",
                    "historical_significance": "Created in 1362 AD by a Banjara nomad and later enlarged by Maharana Udai Singh II after establishing Udaipur.",
                    "best_time_to_visit": "September to March",
                    "entry_fee": "Free entry (Boat rides: ₹400 – ₹800 approx.)",
                    "timings": "6:00 AM – 6:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Lake+Pichola+Udaipur",
                    "nearby_attractions": "Jag Mandir\nLake Palace\nAmbrai Ghat",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Saheliyon Ki Bari",
                    "categories": ["heritage", "gardens"],
                    "description": "A historic landscaped garden adorned with lush marble fountains, lotus pools, kiosk pavilions, and elephant sculptures.",
                    "historical_significance": "Designed in the early 18th century by Maharana Sangram Singh II for the queen and her royal entourage of 48 maidens.",
                    "best_time_to_visit": "September to March",
                    "entry_fee": "₹20 (Indians), ₹100 (Foreigners)",
                    "timings": "9:00 AM – 7:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Saheliyon+Ki+Bari+Udaipur",
                    "nearby_attractions": "Fateh Sagar Lake\nMoti Magri\nSukhadia Circle",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Jaisalmer",
            "places": [
                {
                    "name": "Jaisalmer Fort",
                    "categories": ["heritage", "fort", "unesco"],
                    "description": "One of the world's few functioning 'living forts', constructed with yellow sandstone that glitters like gold in the desert sun (Sonar Qila).",
                    "historical_significance": "Built in 1156 AD by the Rajput king Rawal Jaisal, serving as a critical trading post on the historic Silk Route.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry to fort premises (₹100 – ₹250 for Palace Museum)",
                    "timings": "9:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Jaisalmer+Fort",
                    "nearby_attractions": "Patwon Ki Haveli\nSalim Singh Ki Haveli\nGadisar Lake",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Sam Sand Dunes",
                    "categories": ["nature", "adventure", "desert"],
                    "description": "Expansive desert dunes on the periphery of the Thar Desert, popular for camel safaris, jeep dune bashing, folk music, and stargazing.",
                    "historical_significance": "A cultural hub preserving Rajasthani desert folk traditions, Kalbelia dance forms, and desert life.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (Desert activities & camping charged separately)",
                    "timings": "Open 24 hours (Best experienced at sunrise and sunset)",
                    "location_map_url": "https://maps.google.com/?q=Sam+Sand+Dunes+Jaisalmer",
                    "nearby_attractions": "Desert National Park\nKuldhara Abandoned Village\nKhuri Dunes",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Patwon Ki Haveli",
                    "categories": ["heritage", "architecture"],
                    "description": "A cluster of five intricately carved sandstone mansions featuring delicate jali latticework, miniature paintings, and antique artifacts.",
                    "historical_significance": "Built between 1800 and 1860 by wealthy merchant Guman Chand Patwa for his five sons.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹100 (Indians), ₹250 (Foreigners)",
                    "timings": "9:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Patwon+Ki+Haveli+Jaisalmer",
                    "nearby_attractions": "Jaisalmer Fort\nNathmal Ki Haveli\nSalim Singh Ki Haveli",
                    "is_featured": False,
                    "is_verified": True,
                },
                {
                    "name": "Gadisar Lake",
                    "categories": ["heritage", "lakes"],
                    "description": "A scenic 14th-century water conservation reservoir surrounded by carved sandstone shrines, chhatris, and the ornate Tilon Ki Pol gateway.",
                    "historical_significance": "Built by Maharawal Gadsi Singh in 1367 AD as the sole rainwater reservoir supplying water to arid Jaisalmer.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (Boating: ₹100 – ₹300)",
                    "timings": "Open 24 hours (Boating: 8:00 AM – 8:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Gadisar+Lake+Jaisalmer",
                    "nearby_attractions": "Desert Cultural Centre\nJaisalmer Fort\nFolklore Museum",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ],
}