DATA = {
    "state": {
        "name": "Tamil Nadu",
        "capital": "Chennai",
        "description": "The Land of Temples — celebrated for its monumental Dravidian architecture, classical arts, vibrant festivals, and extensive coastline.",
    },
    "cities": [
        {
            "name": "Chennai",
            "places": [
                {
                    "name": "Kapaleeshwarar Temple",
                    "categories": ["heritage", "temple"],
                    "description": "A stunning Dravidian-style Shiva temple with a vibrant, intricately carved, 37-meter-tall gopuram (gateway tower) and a large sacred tank.",
                    "historical_significance": "Originally built by the Pallavas in the 7th century, the current structure was rebuilt by the Vijayanagara kings in the 16th century after the original was destroyed by the Portuguese.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (Special darshan tickets available)",
                    "timings": "5:00 AM – 12:00 PM & 4:00 PM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Kapaleeshwarar+Temple+Chennai",
                    "nearby_attractions": "Marina Beach\nSanthome Cathedral Basilica\nVivekananda House",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Marina Beach",
                    "categories": ["nature", "beach", "leisure"],
                    "description": "The second longest urban beach in the world, stretching for 13 kilometers along the Coromandel Coast with a bustling promenade.",
                    "historical_significance": "Developed into a promenade in 1881 by the British Governor, it has historically been a significant gathering place for political rallies and public celebrations.",
                    "best_time_to_visit": "November to February",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours (Best visited during sunrise or sunset)",
                    "location_map_url": "https://maps.google.com/?q=Marina+Beach+Chennai",
                    "nearby_attractions": "Fort St. George\nLighthouse\nParthasarathy Temple",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Madurai",
            "places": [
                {
                    "name": "Meenakshi Amman Temple",
                    "categories": ["heritage", "temple", "architecture"],
                    "description": "A historic Hindu temple complex featuring 14 massive gopurams adorned with thousands of colorful mythological figures, dedicated to Goddess Meenakshi and Lord Shiva.",
                    "historical_significance": "The temple is the geographic and ritual center of the ancient city of Madurai and one of the largest temple complexes in India, primarily built by the Nayak rulers between 1623 and 1655.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (Special darshan and museum fees apply)",
                    "timings": "5:00 AM – 12:30 PM & 4:00 PM – 10:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Meenakshi+Amman+Temple+Madurai",
                    "nearby_attractions": "Thirumalai Nayakkar Mahal\nGandhi Memorial Museum\nKoodal Azhagar Temple",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Thirumalai Nayakkar Mahal",
                    "categories": ["heritage", "palace"],
                    "description": "A magnificent 17th-century palace noted for its giant circular pillars, elaborate stuccowork, and a blend of Dravidian and Rajput architectural styles.",
                    "historical_significance": "Erected in 1636 by King Thirumalai Nayak, it was originally four times larger than the current surviving structure, which mainly consists of the main durbar hall.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹10 (Indians), ₹50 (Foreigners)",
                    "timings": "9:00 AM – 5:00 PM (Light & Sound Show in evening)",
                    "location_map_url": "https://maps.google.com/?q=Thirumalai+Nayakkar+Mahal+Madurai",
                    "nearby_attractions": "Meenakshi Amman Temple\nVandiyur Mariamman Teppakulam\nSt. Mary's Cathedral",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Mahabalipuram",
            "places": [
                {
                    "name": "Shore Temple",
                    "categories": ["heritage", "temple", "unesco"],
                    "description": "An iconic 8th-century structural stone temple perched on the shores of the Bay of Bengal, featuring a pyramidal shikhara made of granite blocks.",
                    "historical_significance": "Built during the reign of the Pallava King Rajasimha, it is one of the oldest structural stone temples in South India and a designated UNESCO World Heritage site.",
                    "best_time_to_visit": "October to March (Best visited at sunrise or sunset)",
                    "entry_fee": "₹40 (Indians), ₹600 (Foreigners) (Includes Pancha Rathas entry)",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Shore+Temple+Mahabalipuram",
                    "nearby_attractions": "Pancha Rathas\nArjuna's Penance\nKrishna's Butter Ball",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Pancha Rathas",
                    "categories": ["heritage", "monument", "unesco"],
                    "description": "An astonishing complex of five monolithic rock-cut temples, each carved from a single large rock outcropping to resemble wooden chariots (rathas).",
                    "historical_significance": "Carved during the reign of King Narasimhavarman I in the 7th century, they showcase the evolution of Dravidian architecture and are named after the Pandavas from the Mahabharata.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Covered by Shore Temple ticket",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Pancha+Rathas+Mahabalipuram",
                    "nearby_attractions": "Shore Temple\nMahabalipuram Lighthouse\nDescent of the Ganges",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}