DATA = {
    "state": {
        "name": "Telangana",
        "capital": "Hyderabad",
        "description": "A state that beautifully bridges the ancient and the modern, known for its majestic Deccan heritage, Kakatiya architecture, and world-renowned IT hubs.",
    },
    "cities": [
        {
            "name": "Hyderabad",
            "places": [
                {
                    "name": "Charminar",
                    "categories": ["heritage", "monument", "landmark"],
                    "description": "An iconic 16th-century mosque and monument featuring four grand arches and soaring minarets, surrounded by the bustling Laad Bazaar.",
                    "historical_significance": "Built in 1591 by Muhammad Quli Qutb Shah, the fifth sultan of the Qutb Shahi dynasty, to commemorate the end of a deadly plague in the city.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹25 (Indians), ₹300 (Foreigners)",
                    "timings": "9:00 AM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Charminar+Hyderabad",
                    "nearby_attractions": "Mecca Masjid\nChowmahalla Palace\nLaad Bazaar",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Golconda Fort",
                    "categories": ["heritage", "fort", "architecture"],
                    "description": "A massive, ruined citadel built on a granite hill, famous for its ingenious acoustics, palaces, and formidable defense systems.",
                    "historical_significance": "Originally a mud fort built by the Kakatiyas, it was expanded into a massive granite fortress by the Qutb Shahi kings. It was the principal capital of the Qutb Shahi kings and nearby mines produced the famous Hope and Koh-i-Noor diamonds.",
                    "best_time_to_visit": "October to March (Stay for the evening Light and Sound show)",
                    "entry_fee": "₹25 (Indians), ₹300 (Foreigners)",
                    "timings": "9:00 AM – 5:30 PM",
                    "location_map_url": "https://maps.google.com/?q=Golconda+Fort+Hyderabad",
                    "nearby_attractions": "Qutb Shahi Tombs\nTaramati Baradari\nHussain Sagar Lake",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Salar Jung Museum",
                    "categories": ["heritage", "museum", "art"],
                    "description": "One of India's premier national museums, housing a breathtaking collection of global antiquities, rare manuscripts, and the famous Musical Clock.",
                    "historical_significance": "The museum's massive collection was primarily sourced by one man—Nawab Mir Yousuf Ali Khan (Salar Jung III), who served as the Prime Minister of Hyderabad.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹50 (Indians), ₹500 (Foreigners)",
                    "timings": "10:00 AM – 5:00 PM (Closed on Fridays)",
                    "location_map_url": "https://maps.google.com/?q=Salar+Jung+Museum+Hyderabad",
                    "nearby_attractions": "Charminar\nNizam Museum\nHussain Sagar Lake",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Warangal",
            "places": [
                {
                    "name": "Thousand Pillar Temple",
                    "categories": ["heritage", "temple", "architecture"],
                    "description": "A star-shaped, intricately carved Hindu temple complex dedicated to Lord Shiva, Vishnu, and Surya, built entirely without the use of mortar.",
                    "historical_significance": "Constructed in 1163 AD by King Rudra Deva, it represents a masterpiece of Kakatiya architecture and engineering.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "6:00 AM – 8:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Thousand+Pillar+Temple+Warangal",
                    "nearby_attractions": "Warangal Fort\nBhadrakali Temple\nKakatiya Musical Garden",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Warangal Fort",
                    "categories": ["heritage", "fort", "ruins"],
                    "description": "A 13th-century fort known for its impressive ruins, specifically the four massive stone gateways (Kakatiya Kala Thoranam) that now serve as the official emblem of Telangana.",
                    "historical_significance": "Built by the Kakatiya dynasty rulers, including Queen Rudrama Devi and King Prataparudra. The fort was a symbol of their power until it fell to the Delhi Sultanate.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹15 (Indians), ₹200 (Foreigners)",
                    "timings": "9:00 AM – 8:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Warangal+Fort",
                    "nearby_attractions": "Thousand Pillar Temple\nBhadrakali Lake\nKush Mahal",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Nalgonda",
            "places": [
                {
                    "name": "Nagarjuna Sagar Dam",
                    "categories": ["nature", "engineering", "landmark"],
                    "description": "One of the world's largest and tallest masonry dams, built across the mighty Krishna River, creating a massive, picturesque reservoir.",
                    "historical_significance": "An engineering marvel whose foundation stone was laid by India's first Prime Minister, Jawaharlal Nehru, in 1955. It submerged an ancient Buddhist settlement, the artifacts of which were moved to Nagarjunakonda island.",
                    "best_time_to_visit": "August to February (Especially during monsoons when the gates are open)",
                    "entry_fee": "Free entry to dam (Boating to Nagarjunakonda is approx. ₹150 - ₹200)",
                    "timings": "Dam is visible 24 hours (Boating: 9:00 AM – 4:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Nagarjuna+Sagar+Dam",
                    "nearby_attractions": "Nagarjunakonda Museum\nEthipothala Waterfalls\nDevarakonda Fort",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}