DATA = {
    "state": {
        "name": "Uttar Pradesh",
        "capital": "Lucknow",
        "description": "The heartland of India — home to the iconic Taj Mahal, ancient holy cities along the Ganges, and rich Nawabi culture.",
    },
    "cities": [
        {
            "name": "Agra",
            "places": [
                {
                    "name": "Taj Mahal",
                    "categories": ["heritage", "monument", "unesco"],
                    "description": "An ivory-white marble mausoleum on the right bank of the Yamuna River, globally celebrated as the ultimate symbol of love and a masterpiece of Mughal architecture.",
                    "historical_significance": "Commissioned in 1632 by Mughal Emperor Shah Jahan to house the tomb of his favorite wife, Mumtaz Mahal. It was designated a UNESCO World Heritage site in 1983.",
                    "best_time_to_visit": "October to March (Best visited at sunrise to avoid crowds and heat)",
                    "entry_fee": "₹50 (Indians), ₹1100 (Foreigners) + ₹200 optional fee to enter the main mausoleum",
                    "timings": "30 minutes before sunrise to 30 minutes before sunset (Closed on Fridays)",
                    "location_map_url": "https://maps.google.com/?q=Taj+Mahal+Agra",
                    "nearby_attractions": "Agra Fort\nMehtab Bagh\nTomb of Itimad-ud-Daulah",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Agra Fort",
                    "categories": ["heritage", "fort", "unesco"],
                    "description": "A massive 16th-century red sandstone fortress that served as the main residence of the emperors of the Mughal Dynasty until 1638.",
                    "historical_significance": "Rebuilt by Emperor Akbar on the remains of an ancient site, and later transformed into a palace by his grandson Shah Jahan, who was subsequently imprisoned here by his son Aurangzeb.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹50 (Indians), ₹650 (Foreigners)",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Agra+Fort",
                    "nearby_attractions": "Taj Mahal\nJama Masjid Agra\nMoti Masjid",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Varanasi",
            "places": [
                {
                    "name": "Kashi Vishwanath Temple",
                    "categories": ["heritage", "temple", "spiritual"],
                    "description": "One of the most famous Hindu temples dedicated to Lord Shiva, standing on the western bank of the holy river Ganga.",
                    "historical_significance": "It is one of the twelve Jyotirlingas, the holiest of Shiva temples. The current structure was built in 1780 by the Maratha ruler Ahilyabai Holkar of Indore.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free for General Darshan (Sugam Darshan/VIP entry costs ₹250–₹300)",
                    "timings": "4:00 AM – 11:00 PM (General Darshan is restricted during specific Aarti timings like Bhog Aarti at 11:15 AM)",
                    "location_map_url": "https://maps.google.com/?q=Kashi+Vishwanath+Temple+Varanasi",
                    "nearby_attractions": "Dashashwamedh Ghat\nManikarnika Ghat\nSarnath",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Dashashwamedh Ghat",
                    "categories": ["heritage", "spiritual", "river"],
                    "description": "The main and most spectacular ghat on the Ganges, famous for the vibrant and highly choreographed evening Ganga Aarti ceremony.",
                    "historical_significance": "According to Hindu mythology, Lord Brahma created it to welcome Lord Shiva and sacrificed ten horses during the Dasa-Ashwamedha yajna performed here.",
                    "best_time_to_visit": "October to March (Visit around 6:00 PM for the evening Aarti)",
                    "entry_fee": "Free entry (Boat rides cost extra)",
                    "timings": "Open 24 hours (Ganga Aarti begins shortly after sunset, usually around 6:45 PM)",
                    "location_map_url": "https://maps.google.com/?q=Dashashwamedh+Ghat+Varanasi",
                    "nearby_attractions": "Kashi Vishwanath Temple\nAssi Ghat\nManikarnika Ghat",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Lucknow",
            "places": [
                {
                    "name": "Bara Imambara",
                    "categories": ["heritage", "monument", "architecture"],
                    "description": "A grand shrine complex known for its colossal central hall built without any supporting pillars, and the Bhulbhulaiya, an incredible labyrinth of nearly 1,000 interconnected passageways.",
                    "historical_significance": "Built by Nawab Asaf-ud-Daula in 1784 as a famine relief project to provide employment to his subjects. It showcases magnificent Awadhi architecture.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹50 (Indians), ₹500 (Foreigners)",
                    "timings": "6:00 AM – 5:00 PM (Closed on Mondays)",
                    "location_map_url": "https://maps.google.com/?q=Bara+Imambara+Lucknow",
                    "nearby_attractions": "Chota Imambara\nRumi Darwaza\nBritish Residency",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}