DATA = {
    "state": {
        "name": "Uttarakhand",
        "capital": "Dehradun",
        "description": "Known as 'Devbhoomi' (Land of the Gods) — renowned for its majestic Himalayan peaks, sacred Hindu pilgrimage sites, and scenic hill stations.",
    },
    "cities": [
        {
            "name": "Rishikesh",
            "places": [
                {
                    "name": "Triveni Ghat",
                    "categories": ["heritage", "spiritual", "river"],
                    "description": "A sacred bathing ghat on the banks of the Ganges, famous for its mesmerizing evening Maha Aarti that illuminates the river.",
                    "historical_significance": "Believed in Hindu mythology to be the confluence of three holy rivers (Ganga, Yamuna, and Saraswati) and a site visited by Lord Krishna.",
                    "best_time_to_visit": "September to November & February to May",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours (Maha Aarti is held around 6:00 PM to 7:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Triveni+Ghat+Rishikesh",
                    "nearby_attractions": "Laxman Jhula\nRam Jhula\nParmarth Niketan",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "The Beatles Ashram",
                    "categories": ["heritage", "spiritual", "nature"],
                    "description": "An abandoned, graffiti-covered ashram located within the Rajaji Tiger Reserve, featuring unique meditation domes and nature trails.",
                    "historical_significance": "Formerly the ashram of Maharishi Mahesh Yogi, it gained global fame in 1968 when English rock band The Beatles stayed here to learn Transcendental Meditation.",
                    "best_time_to_visit": "October to April",
                    "entry_fee": "₹150 (Indians), ₹600 (Foreigners)",
                    "timings": "9:00 AM – 4:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Beatles+Ashram+Rishikesh",
                    "nearby_attractions": "Neer Garh Waterfall\nSwarg Ashram\nRajaji National Park",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Nainital",
            "places": [
                {
                    "name": "Naini Lake",
                    "categories": ["nature", "lakes", "leisure"],
                    "description": "A beautiful crescent-shaped freshwater lake situated amidst the Kumaon hills, offering scenic boating and yachting experiences.",
                    "historical_significance": "Mentioned in ancient Hindu scriptures and revered as one of the 64 Shakti Peethas, where the eye (nayan) of Goddess Sati is believed to have fallen.",
                    "best_time_to_visit": "March to June & September to November",
                    "entry_fee": "Free entry (Boating: ₹150 - ₹210 approx.)",
                    "timings": "6:00 AM – 6:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Naini+Lake+Nainital",
                    "nearby_attractions": "Naina Devi Temple\nMall Road\nSnow View Point",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Naina Peak",
                    "categories": ["nature", "adventure"],
                    "description": "Also known as Cheena Peak, it is the highest peak in Nainital (2,615 meters), offering a breathtaking panoramic view of the snow-clad Himalayas.",
                    "historical_significance": "A popular trekking spot established during the British colonial era when Nainital served as the summer capital of the United Provinces.",
                    "best_time_to_visit": "March to June & September to November",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours (Best visited during daylight hours)",
                    "location_map_url": "https://maps.google.com/?q=Naina+Peak+Nainital",
                    "nearby_attractions": "Tiffin Top\nEco Cave Gardens\nHigh Altitude Zoo",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Haridwar",
            "places": [
                {
                    "name": "Har Ki Pauri",
                    "categories": ["heritage", "spiritual", "river"],
                    "description": "A highly revered ghat on the banks of the Ganges, marking the exact point where the river leaves the mountains and enters the plains.",
                    "historical_significance": "Believed to have been built by King Vikramaditya in the 1st century BC; it is the central site of the monumental Kumbh Mela held every 12 years.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours (Ganga Aarti: 5:30 AM - 6:30 AM & 6:00 PM - 7:00 PM depending on season)",
                    "location_map_url": "https://maps.google.com/?q=Har+Ki+Pauri+Haridwar",
                    "nearby_attractions": "Mansa Devi Temple\nChandi Devi Temple\nBharat Mata Mandir",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Mansa Devi Temple",
                    "categories": ["heritage", "temple"],
                    "description": "A prominent Hindu temple dedicated to Goddess Mansa, situated atop the Bilwa Parvat on the Sivalik Hills, accessible via a scenic ropeway ride.",
                    "historical_significance": "Considered a 'Siddh Peetha' (a holy place where desires get fulfilled) and one of the vertices of the sacred triangle in Haridwar.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "Free entry (Ropeway/Cable car: ₹100 - ₹150 approx.)",
                    "timings": "5:00 AM – 12:00 PM & 2:00 PM – 9:00 PM",
                    "location_map_url": "https://maps.google.com/?q=Mansa+Devi+Temple+Haridwar",
                    "nearby_attractions": "Har Ki Pauri\nChandi Devi Temple\nShanti Kunj",
                    "is_featured": False,
                    "is_verified": True,
                },
            ],
        },
    ]
}