DATA = {
    "state": {
        "name": "West Bengal",
        "capital": "Kolkata",
        "description": "A culturally rich eastern state known for its colonial architecture, literary heritage, the Sundarbans mangrove forest, and rolling tea gardens of Darjeeling.",
    },
    "cities": [
        {
            "name": "Kolkata",
            "places": [
                {
                    "name": "Victoria Memorial",
                    "categories": ["heritage", "museum", "monument"],
                    "description": "A majestic white marble museum surrounded by 64 acres of manicured gardens, blending British and Mughal architectural styles.",
                    "historical_significance": "Commissioned by Lord Curzon and built between 1906 and 1921, it is dedicated to the memory of Queen Victoria and now serves as a premier museum of Indian history.",
                    "best_time_to_visit": "October to March",
                    "entry_fee": "₹30 (Indians), ₹500 (Foreigners) for Museum; ₹20 for Gardens only",
                    "timings": "10:00 AM – 6:00 PM (Museum closed on Mondays), 5:30 AM – 6:00 PM (Gardens)",
                    "location_map_url": "https://maps.google.com/?q=Victoria+Memorial+Kolkata",
                    "nearby_attractions": "Maidan\nSt. Paul's Cathedral\nIndian Museum",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Howrah Bridge",
                    "categories": ["heritage", "landmark", "engineering"],
                    "description": "An iconic balanced cantilever bridge spanning the Hooghly River, celebrated as one of the busiest pedestrian and vehicular bridges in the world.",
                    "historical_significance": "Commissioned in 1943 during WWII, it is an engineering marvel constructed entirely from 26,500 tons of high-tensile steel, held together by rivets without a single nut or bolt.",
                    "best_time_to_visit": "October to March (Best seen illuminated at night)",
                    "entry_fee": "Free entry",
                    "timings": "Open 24 hours",
                    "location_map_url": "https://maps.google.com/?q=Howrah+Bridge+Kolkata",
                    "nearby_attractions": "Mullick Ghat Flower Market\nDakshineswar Kali Temple\nBelur Math",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Darjeeling",
            "places": [
                {
                    "name": "Darjeeling Himalayan Railway (Toy Train)",
                    "categories": ["heritage", "adventure", "unesco"],
                    "description": "A legendary 2-foot narrow-gauge railway offering scenic, nostalgic rides through misty hills, dense forests, and world-famous tea gardens.",
                    "historical_significance": "Built between 1879 and 1881 by the British, it was declared a UNESCO World Heritage Site in 1999 for its innovative engineering in mountainous terrain.",
                    "best_time_to_visit": "March to May & September to December",
                    "entry_fee": "Joyride tickets range from ₹1,000 to ₹1,500 approx.",
                    "timings": "Varies by train schedule (Joyrides usually 8:00 AM – 4:00 PM)",
                    "location_map_url": "https://maps.google.com/?q=Darjeeling+Himalayan+Railway",
                    "nearby_attractions": "Batasia Loop\nGhoom Monastery\nTiger Hill",
                    "is_featured": True,
                    "is_verified": True,
                },
                {
                    "name": "Tiger Hill",
                    "categories": ["nature", "viewpoint"],
                    "description": "The highest point in Darjeeling, internationally famous for its spectacular sunrise views illuminating the twin peaks of Mount Kanchenjunga and Mount Everest.",
                    "historical_significance": "Discovered as a prime viewpoint during the British era when Darjeeling was developed as a summer sanatorium for British soldiers.",
                    "best_time_to_visit": "October to December & March to April",
                    "entry_fee": "₹50 approx. (Additional parking fees apply)",
                    "timings": "4:00 AM – 6:00 PM (Best visited between 4:30 AM and 5:00 AM for sunrise)",
                    "location_map_url": "https://maps.google.com/?q=Tiger+Hill+Darjeeling",
                    "nearby_attractions": "Senchal Lake\nDarjeeling Ropeway\nPeace Pagoda",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
        {
            "name": "Sundarbans",
            "places": [
                {
                    "name": "Sundarbans National Park",
                    "categories": ["nature", "wildlife", "unesco"],
                    "description": "A vast, mystical mangrove forest delta formed by the confluence of the Ganges, Brahmaputra, and Meghna rivers, navigated exclusively by boat.",
                    "historical_significance": "Designated a UNESCO World Heritage Site in 1987, it is the largest continuous mangrove forest in the world and the only mangrove habitat for the endangered Royal Bengal Tiger.",
                    "best_time_to_visit": "September to March",
                    "entry_fee": "₹60 (Indians), ₹200 (Foreigners) (Boat and guide charges extra)",
                    "timings": "8:00 AM – 6:00 PM (No entry after sunset)",
                    "location_map_url": "https://maps.google.com/?q=Sundarbans+National+Park",
                    "nearby_attractions": "Sajnekhali Watch Tower\nSudhanyakhali Watch Tower\nDobanki Canopy Walk",
                    "is_featured": True,
                    "is_verified": True,
                },
            ],
        },
    ]
}