# Generated by Django 5.2.17 on 2026-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('heritage', 'Heritage'), ('nature', 'Nature'), ('spiritual', 'Spiritual'), ('adventure', 'Adventure'), ('beach', 'Beach'), ('culture', 'Culture'), ('wildlife', 'Wildlife')], max_length=50, unique=True),
        ),
    ]
