# Generated by Django 5.2.17 on 2026-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_expand_categories_to_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL if not uploaded locally', max_length=1000),
        ),
        migrations.AddField(
            model_name='state',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL if not uploaded locally', max_length=1000),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/'),
        ),
    ]
